events {}

http {
	upstream ms_booking_manager {
		server ms-booking-manager:8081;
	}

	upstream ms_identity {
		server ms-identity:8082;
	}

	upstream ms_penalty_rank {
		server ms-penalty-rank:8083;
	}

	server {
		listen 80;

		location /identity/ {
			proxy_pass http://ms_identity/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header Accept-Encoding "";
			sub_filter '"/openapi.json"' '"/identity/openapi.json"';
			sub_filter '\'/openapi.json\'' '\'/identity/openapi.json\'';
			sub_filter_once off;
		}

		location /penalty/ {
			proxy_pass http://ms_penalty_rank/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header Accept-Encoding "";
			sub_filter '"/openapi.json"' '"/penalty/openapi.json"';
			sub_filter '\'/openapi.json\'' '\'/penalty/openapi.json\'';
			sub_filter_once off;
		}

		location / {
			proxy_pass http://ms_booking_manager/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}
}
